services:
  bot:
    build: .
    image: ghcr.io/x13a/am-rate-bot:latest
    container_name: am-rate-bot
    restart: unless-stopped
    env_file:
      - ./config/bot.env
    volumes:
      - ./certs/cert.pem:/certs/cert.pem:ro
      - ./config/config.toml:/config/config.toml:ro
    networks:
      - nginx
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    logging:
      options:
        max-size: 10m
        max-file: "5"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/:/certs/:ro
    networks:
      - nginx
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    logging:
      options:
        max-size: 10m
        max-file: "5"

networks:
  nginx:
    name: nginx
