services:
  bot:
    build: .
    image: 'am-rate-bot'
    container_name: 'am-rate-bot'
    env_file:
      - 'config/bot.env'
    volumes:
      - './certs/cert.pem:/certs/cert.pem:ro'
    networks:
      - 'nginx-network'
    expose:
      - '8000'

  nginx:
    image: nginx:latest
    container_name: 'nginx'
    restart: unless-stopped
    ports:
      - '88:88'
    volumes:
      - './config/nginx.conf:/etc/nginx/nginx.conf:ro'
      - './certs/:/certs/:ro'
    networks:
      - 'nginx-network'

networks:
  nginx-network:
    driver: bridge
