name: Rust

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.rs'
      - 'Cargo.*'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.rs'
      - 'Cargo.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: cargo build --verbose --features github_ci

    - name: Run tests
      run: cargo test --verbose --features github_ci
